image: macos

install:
- xcode-select -p
- brew install cppcheck eigen pcre poco tinyxml wget bullet bison
- brew install python@3.8
- brew unlink python
- brew link --force python@3.8
- brew install asio tinyxml2 opencv console_bridge openssl
- export OPENSSL_ROOT_DIR=$(brew --prefix openssl)
- brew install log4cxx spdlog cunit qt@5 freetype assimp
- export CMAKE_PREFIX_PATH=$CMAKE_PREFIX_PATH:/usr/local/opt/qt@5
- export PATH=$PATH:/usr/local/opt/qt@5/bin
- brew install graphviz pyqt5 sip
- sudo python3 -m pip install -U \
   argcomplete catkin_pkg colcon-common-extensions coverage \
   cryptography empy flake8 flake8-blind-except flake8-builtins \
   flake8-class-newline flake8-comprehensions flake8-deprecated \
   flake8-docstrings flake8-import-order flake8-quotes ifcfg \
   importlib-metadata lark-parser lxml mock mypy netifaces \
   nose pep8 pydocstyle pydot pygraphviz pyparsing \
   pytest-mock rosdep setuptools vcstool rosdistro
- mkdir -p ~/ros2_foxy/src
- cd ~/ros2_foxy
- wget https://raw.githubusercontent.com/nkalupahana/ros2/master/ros2.repos
- vcs import src < ros2.repos
- cd ~/ros2_foxy/
- colcon build

artifacts:
  - path: ~/ros2_foxy/
    name: ROS2 Foxy

build: off
