name: ROS2 Foxy Workspaces

on:
  workflow_dispatch:
  
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        package: ["ros2-foxy-tools"]
    runs-on: macos-latest
    steps:      
      - name: Setup Workspace
        run: |
          xcode-select -p
          brew install cppcheck eigen pcre poco tinyxml wget bullet bison
          export PATH="/usr/local/opt/bison/bin:$PATH"
          brew install python@3.8
          brew unlink python
          brew link --force python@3.8
          brew install asio tinyxml2 opencv console_bridge openssl
          export OPENSSL_ROOT_DIR=$(brew --prefix openssl)
          brew install log4cxx spdlog cunit qt@5 freetype assimp
          export CMAKE_PREFIX_PATH=$CMAKE_PREFIX_PATH:/usr/local/opt/qt@5
          export PATH=$PATH:/usr/local/opt/qt@5/bin
          brew install graphviz pyqt5 sip
          echo "export GTESTSYS=3" >> .bashrc
          sudo python3 -m pip install -U \
             argcomplete catkin_pkg colcon-common-extensions coverage \
             cryptography empy flake8 flake8-blind-except flake8-builtins \
             flake8-class-newline flake8-comprehensions flake8-deprecated \
             flake8-docstrings flake8-import-order flake8-quotes ifcfg \
             importlib-metadata lark-parser lxml mock mypy netifaces \
             nose pep8 pydocstyle pydot pygraphviz pyparsing \
             pytest-mock rosdep setuptools vcstool rosdistro numpy
      - name: Get ROS2 Foxy
        run: |
          cd ~/
          wget https://github.com/ros2/ros2/releases/download/release-foxy-20201211/ros2-foxy-20201211-macos-amd64.tar.bz2
          mkdir -p ~/ros2_foxy
          cd ~/ros2_foxy
          tar xf ~/ros2-foxy-20201211-macos-amd64.tar.bz2
          . ~/ros2_foxy/ros2-osx/setup.bash
          ros2
      - name: Create Workspace
        run: |
          export PATH="/usr/local/opt/bison/bin:/usr/local/opt/qt@5/bin:$PATH"
          export OPENSSL_ROOT_DIR=$(brew --prefix openssl)
          export CMAKE_PREFIX_PATH=$CMAKE_PREFIX_PATH:/usr/local/opt/qt@5
          . ~/ros2_foxy/ros2-osx/setup.bash
          cd ~/
          mkdir -p ~/ws/src
          cd ~/ws/src 
          wget https://raw.githubusercontent.com/nkalupahana/ros2-foxy-macos/main/$PACKAGE.repos
          vcs import < $PACKAGE.repos
          cd ~/ws
          colcon build
        env:
          PACKAGE: ${{ matrix.package }}
      - name: Package
        run: |
          cd ~/
          zip -r $PACKAGE.zip ~/ros2_foxy/
        env:
          PACKAGE: ${{ matrix.package }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ~/${{ matrix.package }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
