name: code testing

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Test releases
        run: |
          brew install hub
          touch test.txt
          hub release edit -F test.txt ros2-foxy-tools
