name: code testing

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Test releases
        env:
          GITHUB_USER: ${{ secrets.GITHUB_USER }}
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        run: |
          touch test.txt
          hub release edit -m "" -a appveyor.yml ros2-foxy-tools
