name: code testing

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Test
        run: |
          brew install python@3.8
          brew unlink python@3.9
          brew link --force python@3.8
          sudo python3 -m pip install -U vcstool
          mkdir -p ~/ros2_foxy/src
          cd ~/ros2_foxy
          wget https://raw.githubusercontent.com/nkalupahana/ros2/master/ros2.repos
          vcs import src < ros2.repos
          cd ~/
          zip -r ros2_foxy.zip ~/ros2_foxy/
      - uses: actions/upload-artifact@v2
        with:
          name: ros2-foxy
          path: ~/ros2_foxy.zip
          
