name: Testing Action

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Install
        run: |
          brew tap osrf/simulation
          brew update
          brew install osrf/simulation/gazebo11
      - name: Test
        run: brew test osrf/simulation/gazebo11
