name: code testing

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Test releases
        run: |
          ls
          cd ros2-foxy-macos
          brew install hub
          touch test.txt
          hub release edit -F test.txt ros2-foxy-tools
