name: Testing Action

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Test
        run: |
          brew install osrf/simulation/gazebo11
          brew test osrf/simulation/gazebo11
