name: code testing

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Get ROS2 Foxy
        run: |
          mkdir -p ~/ros2_foxy
          cd ~/ros2_foxy
          tar xf ~/Downloads/ros2-release-distro-date-macos-amd64.tar.bz2
          . ~/ros2_foxy/ros2-osx/setup.bash
          ros2
